name: Simple Bot
on:
  issues:
    types: [opened]

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - name: Reply to Issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "你好！虽然你是主人，但我还是检测到你发了新 Issue！"
            })
